version: '2'
services:
  lita:
    build: .
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - .:/code
    ports:
    - '8080:8080'
    environment:
      - LITA_ADAPTER=slack
      - LITA_ROBOT_ADMINS=jdom
    env_file: ./secrets.env
  redis:
    image: redis
    volumes:
      - ./redis:/data
